"""Initial

Revision ID: 3f4570f20e5b
Revises: 
Create Date: 2026-02-16 10:07:43.825519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4570f20e5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_team_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_api_team_id'), 'teams', ['api_team_id'], unique=True)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_game_id', sa.String(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_api_game_id'), 'games', ['api_game_id'], unique=True)
    op.create_index(op.f('ix_games_date'), 'games', ['date'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_player_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_api_player_id'), 'players', ['api_player_id'], unique=True)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('player_boxscores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_boxscores_id'), 'player_boxscores', ['id'], unique=False)
    op.create_table('player_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('rolling_pts_5', sa.Float(), nullable=True),
    sa.Column('rolling_reb_5', sa.Float(), nullable=True),
    sa.Column('rolling_ast_5', sa.Float(), nullable=True),
    sa.Column('matchup_difficulty_score', sa.Float(), nullable=True),
    sa.Column('rest_days', sa.Integer(), nullable=True),
    sa.Column('target_above_avg', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_features_game_id'), 'player_features', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_features_id'), 'player_features', ['id'], unique=False)
    op.create_index(op.f('ix_player_features_player_id'), 'player_features', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_features_player_id'), table_name='player_features')
    op.drop_index(op.f('ix_player_features_id'), table_name='player_features')
    op.drop_index(op.f('ix_player_features_game_id'), table_name='player_features')
    op.drop_table('player_features')
    op.drop_index(op.f('ix_player_boxscores_id'), table_name='player_boxscores')
    op.drop_table('player_boxscores')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_api_player_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_date'), table_name='games')
    op.drop_index(op.f('ix_games_api_game_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_api_team_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
